- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# - name: Print the package facts
#   ansible.builtin.debug:
#     var: ansible_facts.packages

- name: Run GCloud installation
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - google-cloud-sdk
  when: "'google-cloud-sdk' not in ansible_facts.packages"