- name: Install dependencies for GCloud CLI
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg
    - curl
    - software-properties-common